// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2czsQ4hqoXkMi4EEn4jJh5DAGgVMH79w',
    appId: '1:394773950744:web:a9a8c75b0d28e3f2c9ee6d',
    messagingSenderId: '394773950744',
    projectId: 'roomfinder-bfea8',
    authDomain: 'roomfinder-bfea8.firebaseapp.com',
    storageBucket: 'roomfinder-bfea8.appspot.com',
    measurementId: 'G-ZVHXHZ9CGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcCnAXba6clz2r7atwSMPsAkn6ySxj6CY',
    appId: '1:394773950744:android:0295a0574a01acffc9ee6d',
    messagingSenderId: '394773950744',
    projectId: 'roomfinder-bfea8',
    storageBucket: 'roomfinder-bfea8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGglNbC3l5uQaiDdEi35uxaCMl8OIOnCI',
    appId: '1:394773950744:ios:008de9e73bf64290c9ee6d',
    messagingSenderId: '394773950744',
    projectId: 'roomfinder-bfea8',
    storageBucket: 'roomfinder-bfea8.appspot.com',
    iosClientId: '394773950744-ndp7hvco243rkkn8i3dsfdsmqih7vs8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomFinder',
  );
}
